Show test failures with Jackson 2 API 2.19.0 and another plugin
Jenkins plugin BOM fails all tests in convertor classes when run with
Jackson 2 API 2.19.0.  The failure message is:

Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/std/ToEmptyObjectSerializer [in thread "main"]
	at com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.setupModule(JavaTimeModule.java:157)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModules(ObjectMapper.java:1017)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.configureMapper(KubernetesSerialization.java:92)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.<init>(KubernetesSerialization.java:88)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.<init>(KubernetesSerialization.java:76)
	at io.fabric8.kubernetes.client.utils.Serialization.<clinit>(Serialization.java:38)

The ToEmptyObjectSerializer class is included in Jackson API 2.19.0 just as
it was included in earlier releases.

Failures are recorded at:

* https://ci.jenkins.io/job/Tools/job/bom/job/master/4594/testReport/com.cloudbees.jenkins.plugins.kubernetes_credentials_provider/

Passing tests are:

* LabelSelectorExpressionsTest
* SecretUtilsTest
* AbstractConverterTest

All other tests fail when run with Jackson API 2.19.0 and a test
dependency for any of the following plugins:

* Bitbucket Branch Source
* Artifact Manager for S3
* Pipeline Graph View

I didn't search for other examples, since those three examples seem sufficient.